apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: grpc-gateway-sample-2
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: grpc-gateway-sample
    app.kubernetes.io/version: devel
  name: grpc-gateway-sample-2
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/name: tekton-results-api-14
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=63072000
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: grpc-gateway-sample
  name: grpc-gateway-sample
spec:
  path: /
  port:
    targetPort: http-3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: grpc-gateway-sample-2
    weight: 100
  wildcardPolicy: None
status: {}
---
