apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: grpc-gateway-sample-tg7j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grpc-gateway-sample-tg7j
    app.kubernetes.io/part-of: grpc-gateway-sample
    app.kubernetes.io/version: devel
  name: grpc-gateway-sample-tg7j
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: grpc-gateway-sample-tg7j
    app.kubernetes.io/name: none
status:
  loadBalancer: {}
